### ISSUE TITLE
Can't run the Game on Debian because of undefined: MenuScene error

### ISSUE THREAD

**Issue by TechComSpot** [otraore/space-shooter#1]
Hi @otraore.

I have installed all dependencies including go, engo, etc but when I try to run a game I got next error:
![2](https://user-images.githubusercontent.com/9653037/85204607-3a110f80-b2db-11ea-9de7-389a1d48a4a9.png)
Can you advice, please ??

**Comment by otraore** [comment]
You're trying to run the app by only using one file `main.go`, you need to run the all the files in the directory. So run: `go run .` instead of `go run main.go`. Keep in mind this repo isn't all the way up to date with my local stuff and the game isn't really fully playable at the moment.

**Comment by TechComSpot** [comment]
Awesome :))) I did it :)))
Thank you @otraore  for help and a quick response :)
Sorry for such stupid questions.

**Comment by otraore** [comment]
You're fine, your question was not stupid. Hope you have fun messing around with the code, but take everything in here with a grain of salt for now, there's a lot of stuff that's not ideal at the moment.

**Comment by TechComSpot** [comment]
Thank you. No problem I am not a good developer at all, so your code is
fine and the game is good too :)
